version: '3.9'

services:
  datastoryhub:
    build: .
    ports:
      - "8000:8000"   # FastAPI
      # - "8501:8501"   # Streamlit
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload